version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    restart: always
    ports:
      - 5674:5672
      - 15674:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest